name: build tiny artifact

on:
  push:
    branches:
      - '*'

jobs:
  build-tiny-artifact:
    runs-on: ubuntu-20.04

    steps:
      - name: Save date to file to go in app.zip artifact
        run:  |
          date > date.txt
          zip -rT app.zip date.txt
        
      - uses: actions/upload-artifact@v2
        name: Upload app.zip
        with:
          name: artifact
          path: app.zip
