name: build tiny artifact

on:
  push: 
    branches:
      - '*'

jobs:
  build-tiny-artifact:
    runs-on: windows-latest

    steps:
      - name: Save date to file to go in app.zip artifact - https://stackoverflow.com/a/65698504/53897
        run:  |
          echo github=${{github}}
          echo github.action=${{github.action}}
          echo github.action_path=${{github.action_path}}
          echo github.actor=${{github.actor}}
          echo github.base_ref=${{github.base_ref}}
          echo github.event=${{github.event}}
          echo github.event_name=${{github.event_name}}
          echo github.head_ref=${{github.head_ref}}
          echo github.job=${{github.job}}
          echo github.ref=${{github.ref}}
          echo github.repository=${{github.repository}}
          echo github.run_id=${{github.run_id}}
          echo github.run_number=${{github.run_number}}
          echo github.sha=${{github.sha}}
          echo github.token=${{github.token}}
          echo github.workflow=${{github.workflow}}
          echo github.workspace=${{github.workspace}}

          echo "<configuration><ApplicationVersion><GitBranch>${{ github.ref }}</GitBranch><GitCommitHash>${{ github.sha }}</GitCommitHash></ApplicationVersion></configuration>"
          echo "<configuration><ApplicationVersion><GitBranch>${{ github.ref }}</GitBranch><GitCommitHash>${{ github.sha }}</GitCommitHash></ApplicationVersion></configuration>" > version.xml
          date > date.txt
          # zip -rT app.zip date.txt version.xml
          # zip is not available in github windows runners - 7z command found in https://patriksvensson.se/2020/03/creating-release-artifacts-with-github-actions/
          #zip -rT ../app.zip .
          7z a -tzip "app.zip" date.txt version.xml

      # https://github.com/actions/upload-artifact/blob/main/README.md
      - uses: actions/upload-artifact@v2
        name: Upload app.zip
        with:
          name: artifact
          path: app.zip
