name: build tiny artifact

on:
  push:
    branches:
      - '*'

jobs:
  build-tiny-artifact:
    runs-on: windows-latest

    steps:
      - name: Save date to file to go in app.zip artifact
        run:  |
          echo '<configuration><ApplicationVersion><GitBranch%GITHUB_REF%</GitBranch><GitCommitHash>%GITHUB_SHA%</GitCommitHash></ApplicationVersion></configuration>'
          echo '<configuration><ApplicationVersion><GitBranch>%GITHUB_REF%</GitBranch><GitCommitHash>%GITHUB_SHA%</GitCommitHash></ApplicationVersion></configuration>' > version.xml
          date > date.txt
          # zip -rT app.zip date.txt version.xml
          # zip is not available in github windows runners - 7z command found in https://patriksvensson.se/2020/03/creating-release-artifacts-with-github-actions/
          #zip -rT ../app.zip .
          7z a -tzip "app.zip" date.txt version.xml

      # https://github.com/actions/upload-artifact/blob/main/README.md
      - uses: actions/upload-artifact@v2
        name: Upload app.zip
        with:
          name: artifact
          path: app.zip
