name: build tiny artifact

on:
  push:
    branches:
      - '*'

jobs:
  build-tiny-artifact:
    runs-on: ubuntu-20.04

    steps:
      - name: Save date to file to go in app.zip artifact
        run:  |
          echo "<configuration><ApplicationVersion><GitBranch>%GITHUB_REF%</GitBranch><GitCommitHash>%GITHUB_SHA%</GitCommitHash></ApplicationVersion></configuration>" > version.xml
          date > date.txt
          zip -rT app.zip date.txt version.xml

      # https://github.com/actions/upload-artifact/blob/main/README.md
      - uses: actions/upload-artifact@v2
        name: Upload app.zip
        with:
          name: artifact
          path: app.zip
